"""Initial schema

Revision ID: 03f034cfdf0a
Revises: 
Create Date: 2025-11-16 21:47:22.622934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f034cfdf0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_index(op.f('ix_teams_team_name'), 'teams', ['team_name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_name'], ['teams.team_name'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pull_requests',
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('pull_request_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MERGED', name='pr_status_enum'), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pull_request_id')
    )
    op.create_table('pull_request_reviewers',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.pull_request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pull_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_reviewers')
    op.drop_table('pull_requests')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_team_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
